FROM python:3.12-slim-bookworm

# Imposta la directory di lavoro all'interno del container
WORKDIR /app

# Copia solo il file delle dipendenze
COPY requirements.txt .

# Installa le dipendenze Python
RUN pip install --no-cache-dir -r requirements.txt

# Copia il codice sorgente dell'applicazione
COPY . .

# Espone la porta interna 5000 (quella su cui Uvicorn girerà)
EXPOSE 5000

# Definisce la variabile d'ambiente fissa per il Mock
ENV MOCKMONGO="True"
ENV ALGORITHM="HS256"
ENV ACCESS_TOKEN_EXPIRE_MINUTES=30

# Comando di avvio dell'applicazione Uvicorn
# 🟢 NOTA: Rimosse le flag --ssl-keyfile e --ssl-certfile
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]