FROM python:3.12-slim

WORKDIR /app

COPY game_engine/requirements.txt .

RUN pip install -r requirements.txt
RUN pip install pytest==8.2.0 mongomock==4.1.2

COPY game_engine/ .

ENV FLASK_APP=app.py

EXPOSE 5000

CMD ["python", "-m", "flask", "run", "--host=0.0.0.0", "--port=5000"]
