FROM python:3.12-slim

WORKDIR /app

COPY collection/requirements.txt .

RUN pip install -r requirements.txt

COPY collection/app.py .
COPY collection/utilities.py .
COPY collection/app_test.py .
COPY collection/cards/ ./cards/

EXPOSE 5000

CMD ["flask", "--app", "app_test", "run", "--host=0.0.0.0", "--port=5000"]