FROM python:3.12.3-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt
RUN pip install mongomock==4.1.2

COPY . .

EXPOSE 5000

CMD ["flask", "--app", "app_test", "run", "--host=0.0.0.0", "--port=5000"]