FROM python:3.12-slim

WORKDIR /history

COPY requirements.txt .

RUN pip install -r requirements.txt
RUN pip install mongomock

COPY . .

ENV FLASK_APP=app_test.py

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
